### ISSUE TITLE
uninitialized constant Rails (NameError) upon require

### ISSUE THREAD

**Issue by mensfeld** [ryankopf/antispam#1]
h1. Error upon require

My name is Maciej Mensfeld and I run a research security project called https://diffend.io.

While that's not a security issue, wanted to bring to your attention, that upon requiring of this gem (diffend does that to run a sandbox for security assessment of gems based on their behaviors), it fails with:

<pre>
lib/antispam/engine.rb:2:in `<module:Antispam>': uninitialized constant Rails (NameError)
</pre>

which (probably) indicates, that `rails` is not present upon loading.

repro:

Gemfile

<pre><code class="ruby">
source 'https://rubygems.org'

gem 'antispam'
</code></pre>

steps:

1. bundle install
2. bundle exec ruby -e 'require "antispam"'

**Comment by ryankopf** [comment]
This gem can not be used outside of a Rails app.
